Bug fix/rotate
StarSimVR/godot pull request #5
Opened 2022-07-04 18:28 UTC by kevinmatthes

This Pull Request aims to fix #3 and #4.

2022-07-04 19:26 UTC, kevinmatthes commented on project/scenes/scene_decoder.gd
> +		node.transform.origin = centre + radius * Vector3(cos(phi), sin(phi), 0)
This looks basically like a scaled and translated unit circle -- a *full* unit circle.

Is there an area around the centre cut out or does this really mean that the circle intersects the planet surrounded by the belt, meaning some objects *might* be created within it?

2022-07-04 19:28 UTC, kevinmatthes commented
I drafted this Pull Request since there might be a performance leak due to the definition of the coordinate area.

2022-07-05 14:30 UTC, kevinmatthes commented on project/scenes/scene_decoder.gd
> +		node.transform.origin = centre + radius * Vector3(cos(phi), sin(phi), 0)
Okay, now I understood.  It is a cylinder with a cut-out centre.

2022-07-07 10:18 UTC, Ranplax requested changes
This commit should not be included, since the changes will be obsolete after the fix. They therefore do not belong in the merge.

2022-07-07 14:31 UTC, kevinmatthes commented
The changes can just be reverted before the merge.  All commits will be squashed anyway, so that does not matter.  Alternative:  rebase the commit into a new branch and force push the other commits after it.

2022-07-13 14:14 UTC, closed without merging